name: deploy prod branch

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy-front:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.TARGET_PATH }}
            git checkout prod
            git pull origin prod
            sudo docker-compose up --build -d
